import { PatientContextProvider } from "@/context/PatientContext";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Patient management",
  description: "Generated by Caspar Health",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <PatientContextProvider>{children}</PatientContextProvider>
      </body>
    </html>
  );
}
